if (SERVER) then 
AddCSLuaFile( "cbb_miku_append_chibi2.lua" )
player_manager.AddValidModel( "Tda Chibi Miku Append (v2)", "models/captainbigbutt/vocaloid/chibi_miku_ap.mdl" )
player_manager.AddValidHands( "Tda Chibi Miku Append (v2)", "models/captainbigbutt/vocaloid/c_arms/miku_append.mdl", 0, "00000000" )
end

--Add Playermodel
player_manager.AddValidModel( "Tda Chibi Miku Append (v2)", "models/captainbigbutt/vocaloid/chibi_miku_ap.mdl" )
player_manager.AddValidHands( "Tda Chibi Miku Append (v2)", "models/captainbigbutt/vocaloid/c_arms/miku_append.mdl", 0, "00000000" )

list.Set( "PlayerOptionsModel", "Tda Chibi Miku Append (v2)", 	"models/captainbigbutt/vocaloid/chibi_miku_ap.mdl" )

--Add NPC
local NPC =
{
	Name = "Tda Chibi Miku Append(v2)",
	Class = "npc_citizen",
	KeyValues = { citizentype = 4 },
	Model = "models/captainbigbutt/vocaloid/npc/chibi_miku_ap.mdl",
	Category = "Vocaloid"
}

list.Set( "NPC", "npc_cbb_cmikuappend2", NPC )



-- Send this to clients automatically so server hosts don't have to
--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/chibi_miku_ap/chibi_body.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/chibi_miku_ap/chibi_body.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/chibi_miku_ap/chibi_body02.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/chibi_miku_ap/chibi_body02.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/basewarp.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/body.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/body.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/body02.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/body02.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/body_illum.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/body_illum02.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/body_misc.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/body_misc.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/eye.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/eye02.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/face.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/face.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/face02.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/face02.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/facewarp.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/face_misc.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/hair.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/hair.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/hair02.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/hair02.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/hairwarp.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/hairwarp02.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/hair_default.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/hair_default.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/hair_illum.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/lights.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/lights02.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/lightwarp.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/normal.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/phong_exp.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/shadow.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/skin.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/skin02.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/skinwarp.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech02.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech02.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech_illum.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech_illum02.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech_small.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech_small.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech_small02.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tech_small02.vtf" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/tie.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/wing.vmt" )
	resource.AddFile( "materials/models/captainbigbutt/vocaloid/miku_append/wing.vtf" )
	resource.AddFile( "materials/vgui/entities/npc_cbb_cmikuappend2.vmt" )
	resource.AddFile( "materials/vgui/entities/npc_cbb_cmikuappend2.vtf" )
	resource.AddFile( "models/captainbigbutt/vocaloid/chibi_miku_ap.dx80.vtx" )
	resource.AddFile( "models/captainbigbutt/vocaloid/chibi_miku_ap.dx90.vtx" )
	resource.AddFile( "models/captainbigbutt/vocaloid/chibi_miku_ap.mdl" )
	resource.AddFile( "models/captainbigbutt/vocaloid/chibi_miku_ap.phy" )
	resource.AddFile( "models/captainbigbutt/vocaloid/chibi_miku_ap.sw.vtx" )
	resource.AddFile( "models/captainbigbutt/vocaloid/chibi_miku_ap.vvd" )
	resource.AddFile( "models/captainbigbutt/vocaloid/c_arms/miku_append.dx80.vtx" )
	resource.AddFile( "models/captainbigbutt/vocaloid/c_arms/miku_append.dx90.vtx" )
	resource.AddFile( "models/captainbigbutt/vocaloid/c_arms/miku_append.mdl" )
	resource.AddFile( "models/captainbigbutt/vocaloid/c_arms/miku_append.sw.vtx" )
	resource.AddFile( "models/captainbigbutt/vocaloid/c_arms/miku_append.vvd" )
	resource.AddFile( "models/captainbigbutt/vocaloid/npc/chibi_miku_ap.dx80.vtx" )
	resource.AddFile( "models/captainbigbutt/vocaloid/npc/chibi_miku_ap.dx90.vtx" )
	resource.AddFile( "models/captainbigbutt/vocaloid/npc/chibi_miku_ap.mdl" )
	resource.AddFile( "models/captainbigbutt/vocaloid/npc/chibi_miku_ap.phy" )
	resource.AddFile( "models/captainbigbutt/vocaloid/npc/chibi_miku_ap.sw.vtx" )
	resource.AddFile( "models/captainbigbutt/vocaloid/npc/chibi_miku_ap.vvd" )
	resource.AddFile( "models/chibi_anm.mdl" )
end