if (SERVER) then 
player_manager.AddValidModel( "Tda Chibi Kuro Miku Append (v2)", "models/_Skele_Dragon_/vocaloid/chibi_kuro_ap.mdl" )
player_manager.AddValidHands( "Tda Chibi Kuro Miku Append (v2)", "models/_Skele_Dragon_/vocaloid/c_arms/kuro_append.mdl", 0, "00000000" )
AddCSLuaFile( "skd_kuro_append_chibi2.lua" )
end

--Add Playermodel
player_manager.AddValidModel( "Tda Chibi Kuro Miku Append (v2)", "models/_Skele_Dragon_/vocaloid/chibi_kuro_ap.mdl" )
--Sorry, custom chibi miku hands didn't really work out so well
--http://i.imgur.com/y4ANpsr.jpg
player_manager.AddValidHands( "Tda Chibi Kuro Miku Append (v2)", "models/_Skele_Dragon_/vocaloid/c_arms/kuro_append.mdl", 0, "00000000" )

list.Set( "PlayerOptionsModel", "Tda Chibi Kuro Miku Append (v2)", 	"models/_Skele_Dragon_/vocaloid/chibi_kuro_ap.mdl" )

--Add NPC
local NPC =
{
	Name = "Tda Chibi Kuro Miku Append(v2)",
	Class = "npc_citizen",
	KeyValues = { citizentype = 4 },
	Model = "models/_Skele_Dragon_/vocaloid/npc/chibi_kuro_ap.mdl",
	Category = "Vocaloid"
}

list.Set( "NPC", "npc_skd_ckuroappend2", NPC )




-- Send this to clients automatically so server hosts don't have to
--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/chibi_kuro_ap/chibi_body.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/chibi_kuro_ap/chibi_body.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/chibi_kuro_ap/chibi_body02.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/chibi_kuro_ap/chibi_body02.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/basewarp.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/body.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/body.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/body02.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/body02.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/body_illum.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/body_misc.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/body_misc.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/eye.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/face.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/face.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/facewarp.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/face_illum.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/face_misc.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/hair.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/hair.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/hair02.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/hair02.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/hairwarp.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/hairwarp02.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/hair_illum.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/lights.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/lightwarp.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/normal.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/phong_exp.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/shadow.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/skin.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/skin02.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/skinwarp.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/tech.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/tech.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/tech_illum.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/tech_small.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/tech_small.vtf" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/tie.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/wing.vmt" )
	resource.AddFile( "materials/models/_Skele_Dragon_/vocaloid/kuro_append/wing.vtf" )
	resource.AddFile( "materials/vgui/entities/npc_skd_ckuroappend2.vmt" )
	resource.AddFile( "materials/vgui/entities/npc_skd_ckuroappend2.vtf" )
	resource.AddFile( "models/chibi_anm.mdl" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/chibi_kuro_ap.dx80.vtx" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/chibi_kuro_ap.dx90.vtx" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/chibi_kuro_ap.mdl" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/chibi_kuro_ap.phy" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/chibi_kuro_ap.sw.vtx" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/chibi_kuro_ap.vvd" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/c_arms/kuro_append.dx80.vtx" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/c_arms/kuro_append.dx90.vtx" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/c_arms/kuro_append.mdl" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/c_arms/kuro_append.sw.vtx" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/c_arms/kuro_append.vvd" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/npc/chibi_kuro_ap.dx80.vtx" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/npc/chibi_kuro_ap.dx90.vtx" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/npc/chibi_kuro_ap.mdl" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/npc/chibi_kuro_ap.phy" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/npc/chibi_kuro_ap.sw.vtx" )
	resource.AddFile( "models/_Skele_Dragon_/vocaloid/npc/chibi_kuro_ap.vvd" )
end