esstx.snowball=Сніжок
esstx.ins=Просто кинь його!)

esstx.checkbox.infsnwb.t=Нескінченні сніжки
esstx.checkbox.expsnwb.t=Вибухові сніжки
esstx.checkbox.flmsnwb.t=Вогняні сніжки
esstx.checkbox.ndsnwb.t=Вимкнути шкоду

esstx.checkbox.cangrabsnowballgrass.t=Гравець може підібрати сніжок із трави
esstx.checkbox.cangrabsnowballgrass.d=Використовуйте цю опцію, якщо у вас встановлені аддони, такі як "Snow!" від Mee

esstx.checkbox.bellsnd.t=Звук, коли гравець бере сніжок із меню спавна
esstx.checkbox.bellsnd.d=Цей звук дзвіночка відтворюватиметься щоразу, коли гравець бере сніжок із меню спавна

esstx.rateit=Сподобався аддон? Постав лайк)

esstx.snowballsettings=Налаштування сніжка