list.Set( "PlayerOptionsModel", "SA - Sonic the Hedgehog", "models/Luria/Sonic_Adventure/Sonic.mdl" )
player_manager.AddValidModel( "SA - Sonic the Hedgehog", "models/Luria/Sonic_Adventure/Sonic.mdl" )
player_manager.AddValidHands( "SA - Sonic the Hedgehog", "models/Luria/Sonic_Adventure/C_Arms_Sonic.mdl", 0, "00000000" )

list.Set( "PlayerOptionsModel", "SA - Miles 'Tails' Prower", "models/Luria/Sonic_Adventure/Tails.mdl" )
player_manager.AddValidModel( "SA - Miles 'Tails' Prower", "models/Luria/Sonic_Adventure/Tails.mdl" )
player_manager.AddValidHands( "SA - Miles 'Tails' Prower", "models/Luria/Sonic_Adventure/C_Arms_Tails.mdl", 0, "00000000" )

list.Set( "PlayerOptionsModel", "SA - Knuckles the Echidna", "models/Luria/Sonic_Adventure/Knuckles.mdl" )
player_manager.AddValidModel( "SA - Knuckles the Echidna", "models/Luria/Sonic_Adventure/Knuckles.mdl" )
player_manager.AddValidHands( "SA - Knuckles the Echidna", "models/Luria/Sonic_Adventure/C_Arms_Knuckles.mdl", 0, "00000000" )

list.Set( "PlayerOptionsModel", "SA - Amy Rose", "models/Luria/Sonic_Adventure/Amy.mdl" )
player_manager.AddValidModel( "SA - Amy Rose", "models/Luria/Sonic_Adventure/Amy.mdl" )
player_manager.AddValidHands( "SA - Amy Rose", "models/Luria/Sonic_Adventure/C_Arms_Amy.mdl", 0, "00000000" )

--PRECACHING--

--Models

util.PrecacheModel( "models/Luria/Sonic_Adventure/Sonic.mdl" )
util.PrecacheModel( "models/Luria/Sonic_Adventure/C_Arms_Sonic.mdl" )

util.PrecacheModel( "models/Luria/Sonic_Adventure/Tails.mdl" )
util.PrecacheModel( "models/Luria/Sonic_Adventure/C_Arms_Tails.mdl" )

util.PrecacheModel( "models/Luria/Sonic_Adventure/Knuckles.mdl" )
util.PrecacheModel( "models/Luria/Sonic_Adventure/C_Arms_Knuckles.mdl" )

util.PrecacheModel( "models/Luria/Sonic_Adventure/Amy.mdl" )
util.PrecacheModel( "models/Luria/Sonic_Adventure/C_Arms_Amy.mdl" )

--Death / Drown Sounds

util.PrecacheSound( "Sonic_Adventure/Sonic/drown.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/death1.wav" )

util.PrecacheSound( "Sonic_Adventure/Tails/drown.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/death7.wav" )

util.PrecacheSound( "Sonic_Adventure/Knuckles/drown.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/death3.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/pain1.wav" )

util.PrecacheSound( "Sonic_Adventure/Amy/drown.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/death1.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/death2.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/death3.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/death4.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/death5.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/death6.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/death7.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/death8.wav" )

--Hurt Sounds

util.PrecacheSound( "Sonic_Adventure/Sonic/pain1.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/pain2.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/pain3.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/pain4.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/pain5.wav" )

util.PrecacheSound( "Sonic_Adventure/Tails/pain1.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/pain2.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/pain3.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/pain4.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/pain5.wav" )

util.PrecacheSound( "Sonic_Adventure/Knuckles/pain1.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/pain2.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/pain3.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/pain4.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/pain5.wav" )

util.PrecacheSound( "Sonic_Adventure/Amy/pain1.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain2.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain3.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain4.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain5.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain6.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain7.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain8.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain9.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain10.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/pain11.wav" )

--Spawn Sounds

util.PrecacheSound( "Sonic_Adventure/Sonic/intro1.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro2.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro3.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro4.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro5.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro6.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro7.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro8.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro9.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro10.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro11.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro12.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro13.wav" )
util.PrecacheSound( "Sonic_Adventure/Sonic/intro14.wav" )

util.PrecacheSound( "Sonic_Adventure/Tails/intro1.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro2.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro3.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro4.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro5.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro6.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro7.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro8.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro9.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro10.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro11.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro12.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro13.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro14.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro15.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro16.wav" )
util.PrecacheSound( "Sonic_Adventure/Tails/intro17.wav" )

util.PrecacheSound( "Sonic_Adventure/Knuckles/intro1.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro2.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro3.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro4.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro5.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro6.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro7.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro8.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro9.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro10.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro11.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro12.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro13.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro14.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro15.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro16.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro17.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro18.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro19.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro20.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro21.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro22.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro23.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro24.wav" )
util.PrecacheSound( "Sonic_Adventure/Knuckles/intro25.wav" )

util.PrecacheSound( "Sonic_Adventure/Amy/intro1.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro2.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro3.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro4.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro5.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro6.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro7.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro8.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro9.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro10.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro11.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro12.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro13.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro14.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro15.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro16.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro17.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro18.wav" )
util.PrecacheSound( "Sonic_Adventure/Amy/intro19.wav" )