esstx.snowball=Śnieżka
esstx.ins=Po prostu rzuć!

esstx.checkbox.infsnwb.t=Śnieżki Nieskończoności
esstx.checkbox.expsnwb.t=Wybuchowe śnieżki
esstx.checkbox.flmsnwb.t=Płonące śnieżki
esstx.checkbox.ndsnwb.t=Wyłącz obrażenia

esstx.checkbox.cangrabsnowballgrass.t=Gracz może podnieść kulę śnieżną z trawy
esstx.checkbox.cangrabsnowballgrass.d=Użyj tej opcji, jeśli masz zainstalowane dodatki, takie jak "Snow!" przez Mee

esstx.checkbox.bellsnd.t=Dźwięk, gdy gracz podnosi śnieżkę z spawnmenu
esstx.checkbox.bellsnd.d=Ten dźwięk dzwonka będzie odtwarzany za każdym razem, gdy gracz podniesie śnieżkę z spawnmenu

esstx.rateit=Jeśli podobał ci się ten dodatek, oceń go!

esstx.snowballsettings=Ustawienia kuli śnieżnej