esstx.snowball=雪球
esstx.ins=向你的朋友们投掷雪球!

esstx.checkbox.infsnwb.t=无尽的雪球
esstx.checkbox.expsnwb.t=爆炸性雪球
esstx.checkbox.flmsnwb.t=火焰雪球
esstx.checkbox.ndsnwb.t=无损伤

esstx.checkbox.cangrabsnowballgrass.t=玩家可以从草地上抓取雪球
esstx.checkbox.cangrabsnowballgrass.d=如果你安装了Mee的 "Snow!"等插件，请使用此选项。

esstx.checkbox.bellsnd.t=当玩家从Spawnmenu中拿起雪球时的声音
esstx.checkbox.bellsnd.d=每当有玩家捡起雪球时 会有一条音效

esstx.rateit=如果你喜欢这个插件，请给它评分!

esstx.snowballsettings=雪球设置