esstx.snowball=Snowball
esstx.ins=Just throw it!

esstx.checkbox.infsnwb.t=Infinity Snowballs
esstx.checkbox.expsnwb.t=Explosive Snowballs
esstx.checkbox.flmsnwb.t=Flaming Snowballs
esstx.checkbox.ndsnwb.t=Disable damage

esstx.checkbox.cangrabsnowballgrass.t=Player can pick up a snowball from the grass
esstx.checkbox.cangrabsnowballgrass.d=Use this option if you have addons installed like "Snow!" by Mee

esstx.checkbox.bellsnd.t=The sound when a player picks up a snowball from spawnmenu
esstx.checkbox.bellsnd.d=This bell sound will play every time a player picks up a snowball from the spawnmenu

esstx.rateit=If u liked this addon, pls rate it!

esstx.snowballsettings=Snowball Settings