esstx.snowball=Снежок
esstx.ins=Просто брось его!)

esstx.checkbox.infsnwb.t=Бесконечные снежки
esstx.checkbox.expsnwb.t=Взрывные снежки
esstx.checkbox.flmsnwb.t=Огненные снежки
esstx.checkbox.ndsnwb.t=Отключить урон

esstx.checkbox.cangrabsnowballgrass.t=Игрок может подобрать снежок с травы
esstx.checkbox.cangrabsnowballgrass.d=Используйте эту опцию, если у вас установлены аддоны, такие как "Snow!" от Mee

esstx.checkbox.bellsnd.t=Звук, когда игрок берёт снежок из меню спавна
esstx.checkbox.bellsnd.d=Этот звук колокольчика будет воспроизводиться каждый раз, когда игрок берет снежок из меню спавна

esstx.rateit=Понравился аддон? Поставь лайк)

esstx.snowballsettings=Настройки снежка