esstx.snowball=スノーボール
esstx.ins=とにかく投げろ!

esstx.checkbox.infsnwb.t=インフィニティ・スノーボール
esstx.checkbox.expsnwb.t=爆発する雪玉
esstx.checkbox.flmsnwb.t=炎の雪玉
esstx.checkbox.ndsnwb.t=損傷なし

esstx.checkbox.cangrabsnowballgrass.t=草むらから雪玉をつかめるようになる
esstx.checkbox.cangrabsnowballgrass.d=Meeの "Snow!"などのアドオンがインストールされている場合は、このオプションを使用します。

esstx.checkbox.bellsnd.t=プレイヤーが spawnmenu から雪玉を拾ったときの音
esstx.checkbox.bellsnd.d=このベルの音は、プレイヤーがスポーンメニューから雪玉を拾うたびに再生されます

esstx.rateit=このアドオンが気に入ったら、評価してください!

esstx.snowballsettings=スノーボールの設定